### ISSUE TITLE
 openshift_auth not using group/k8s vars

### ISSUE THREAD

**Issue by pseguel-redhat** [openshift/community.okd#174] opened 2022-09-27 13:36 UTC
Example in openshift_auth is not working because is not taking into account modules defaults (group/k8s). 

Is there a module_defaults available for openshift modules?

**Comment by tima** [comment] 2022-09-27 14:54
@pseguel-redhat What version of ansible are you running into this? Have you tried to reproduced this with the latest stable version?

**Comment by pseguel-redhat** [comment] 2022-09-27 15:13
```
$ ansible --version
ansible [core 2.13.4]
  config file = /Users/pauloseguel/Desktop/ACM_Observability/ansible.cfg
  configured module search path = ['/Users/pauloseguel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/pauloseguel/Desktop/ACM_Tests/myenv/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/pauloseguel/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/pauloseguel/Desktop/ACM_Tests/myenv/bin/ansible
  python version = 3.9.6 (default, Aug  5 2022, 15:21:02) [Clang 14.0.0 (clang-1400.0.29.102)]
  jinja version = 3.1.2
  libyaml = True
```

**Comment by gravesm** [comment] 2022-09-27 18:30
@pseguel-redhat It looks like the example is incorrect. I just tested locally with ansible 2.13 and community.okd 2.2.0 and the following correctly applies the module defaults:
```yaml
- hosts: localhost
  module_defaults:
    group/community.okd.okd:
      host: https://example.com
  tasks:
    - community.okd.openshift_auth:
        username: admin
        password: somepassword
```

**Comment by pseguel-redhat** [comment] 2022-09-27 18:51
It works with my playbooks, thanks.

**Comment by tima** [comment] 2022-09-27 20:27
Closing. We'll track this documentation issues in #175.

**Closed by tima** 2022-09-27 20:27 UTC
Labels: verified, kind/documentation
